# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15K85Sn10pE_2jXmKSCMMO989ErtY_ARl
"""

!pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

pairs = [
    ['No thanks ', ['no problem im here if you need me ']],
    ['Yes i would', ['Greate what is your email adress ']],
    ["\@", ['Thank you would you like to get a discount for your next purchase ?']],
    ['Yes ', ['awesome here is your discount code[2121] have a greate shopping day']],
]

def chatbot():
    print("would you like to subscribe to our news letter to get the latest info on our products? ")
    chat = Chat(pairs, reflections)
    while True:
        try:
            user_input = input("> ")
            if user_input.lower() == 'quit':
                print("Goodbye!")
                break
            response = chat.respond(user_input)
            print(response)
        except KeyboardInterrupt:
            print("Goodbye!")
            break

chatbot()

